source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.2'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use ActiveStorage variant
# gem 'mini_magick', '~> 4.8'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
# gem 'rack-cors', :require => 'rack/cors

# authenticate admin to open admin panel
gem 'devise', '~> 4.5.0'
# admin panel CMS
gem 'activeadmin', '~> 1.4.3'
gem 'active_admin_flat_skin', '~> 0.1.2'
gem "font-awesome-rails", '~> 4.7.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Encoding and decoding user data
gem 'jwt', '~> 2.1.0'
# Validate Credentials
gem 'simple_command', '~> 0.0.9'
# File uploader
gem 'carrierwave', '~> 1.0'
gem 'mini_magick', '~> 4.9.2' # For different versions of an image

gem 'mailgun-ruby', '~>1.1.6'
gem 'local_time', '~> 2.1.0'
gem 'mailchimp-api', require: 'mailchimp'
gem 'active_model_serializers', '~> 0.10.0'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # Capistrano
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

gem "unicorn"
gem "thin"
gem "passenger"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
